export const data = [
    {
      name: "Document",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
      status: "incomplete",
      date: "2021-08-25",
    },
    {
      name: "Document",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
      status: "incomplete",
      date: "2021-08-25",
    },
    {
      name: "Document",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
      status: "incomplete",
      date: "2021-08-25",
    },
    {
      name: "Document",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
      status: "incomplete",
      date: "2021-08-25",
    },
    {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
      {
        name: "Document",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam, tenetur.",
        status: "incomplete",
        date: "2021-08-25",
      },
  ];